import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:fluttertoast/fluttertoast.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  var guessController = TextEditingController();
  var randomNum = 0;
  var random = Random();

  @override
  void initState() {
    super.initState();

    randomNum = random.nextInt(100) + 1;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Random Number Guess'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(15.0),
        child: SingleChildScrollView(
          child: Column(
            children: [
              const Text(
                'A number has been generated by the system from 1 to 100\nTry to guess it',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.w500),
                textAlign: TextAlign.center,
              ),
              const SizedBox(
                height: 20,
              ),
              TextField(
                controller: guessController,
                keyboardType: TextInputType.number,
                decoration: InputDecoration(
                    hintText: 'Enter Your Guess',
                    labelText: 'Enter Your Guess',
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(15.0),
                    )),
              ),
              ElevatedButton(
                  onPressed: () {
                    String userGuess = guessController.text.trim();
                    if (userGuess.isEmpty) {
                      Fluttertoast.showToast(msg: 'Please provide number');
                    } else {
                      int num = int.parse(userGuess);

                      if (num > randomNum) {
                        showResult('High');
                      } else if (num < randomNum) {
                        showResult('Low');
                      } else {
                        showDialog(
                            context: context,
                            builder: (context) {
                              return AlertDialog(
                                title: const Text('Congratulations!'),
                                content:
                                    const Text('You have guessed the number'),
                                actions: [
                                  TextButton(
                                      onPressed: () {
                                        Navigator.of(context).pop();

                                        // regenerate a random number

                                        setState(() {
                                          randomNum = random.nextInt(100) + 1;
                                        });

                                        guessController.text = '';
                                      },
                                      child: const Text('Play Again')),
                                  TextButton(
                                      onPressed: () {
                                        Navigator.of(context).pop();
                                        if (Platform.isAndroid) {
                                          SystemNavigator.pop();
                                        } else if (Platform.isIOS) {
                                          exit(0);
                                        }
                                        // close app
                                      },
                                      child: const Text('Exit')),
                                ],
                              );
                            });
                      }
                    }
                  },
                  child: const Text('Check')),
            ],
          ),
        ),
      ),
    );
  }

  showResult(String type) {
    showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: Text('Your Guess is $type'),
            actions: [
              TextButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                  child: const Text('Okay'))
            ],
          );
        });
  }
}
